### ISSUE TITLE
Semantic Version error on platform

### ISSUE THREAD

**Issue by confact** [watzon/browser#3]
I updated my browser and OS and started to get these errors through on my code:
```shell
browser.platform.name # => Unhandled exception: Not a semantic version: " 10.12" (ArgumentError)
  from /opt/homebrew/Cellar/crystal/1.4.1/src/semantic_version.cr:43:7 in 'parse'
```

User-Agent: 
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36
```

Could it be the space in the front there that shouldn't be there?

**Comment by confact** [comment]
By changing line 9 on `src/browser/platform/mac.cr` to:
```
browser.platform.mac?(">=10.12.0")
```

It seems to work. But that seems a bit like a bug in the semantic version to be needed to add a zero to handle versions.

**Comment by watzon** [comment]
Sorry it took me so long to get to this. I just released a pretty major update that should fix all version errors. In short I'm no longer relying on the semantic versioning shard.
